<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

# What to expect in this chapter

# 1 Lists, Arrays & Dictionaries

## 1.1 Let’s compare

In [1]:
import numpy as np

#list
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

#array
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

#dictionary

superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}

## 1.2 Accessing data from a list (or array)

In [4]:
#Python is a zero-indexed language, meaning it starts counting at 0. 

print(py_real_names[0])
print(py_super_names[0])
print(py_real_names[1])
print(py_super_names[1])

Natasha Romanoff
Black Widow
Tony Stark
Iron Man


In [5]:
#Using a negative index allows us to count from the back of the list. 
#For instance, using the index -1 will give the last element. 
#This is super useful because we can easily access the last element without knowing the list size.

print(py_real_names[-1])
print(py_super_names[-1])
print(py_real_names[-2])
print(py_super_names[-2])

Stephen Strange
Doctor Strange
Tony Stark
Iron Man


## 1.3 Accessing data from a dictionary

In [6]:
#dictionaries hold values paired with a key. 

superhero_info[py_real_names[-1]] #Key in this case is the real name.

'Doctor Strange'

In [7]:
#Note: you can't use a value to find a key

superhero_info[py_super_names[-1]]

KeyError: 'Doctor Strange'

In [9]:
superhero_info.keys()

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

In [10]:
superhero_info.values()

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

## 1.4 Higher dimensional lists

In [17]:
#Unlike with a dictionary, we needed two lists to store the corresponding real and superhero names. 
#An obvious way around the need to have two lists is to have a 2D list (or array) as follows.

py_superhero_info = [['Natasha Romanoff', 'Black Widow',"dead"],
                     ['Tony Stark', 'Iron Man',"dead"],
                     ['Stephen Strange', 'Doctor Strange',"alive"]]

np_superhero_info = np.array(py_superhero_info) # Reusing the Python list 
                                                # to create a NEW
                                                # NumPy array

# 2 Lists vs. Arrays

## 2.1 Size

In [12]:
len(py_superhero_info)

3

In [14]:
len(np_superhero_info)

3

In [18]:
np_superhero_info.shape #shape is not a function but an attribute of the array
                        #returns in the form of (length,number of items in each internal list)

(3, 3)

In [16]:
py_list_2d = [[1, "A", "meh"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list to create a NEW NumPy array
                                        
np_array_2d.shape #Note: array needs to have homogeneous shape. Same number of elements within each list.

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (10,) + inhomogeneous part.

## 2.2 Arrays are fussy about type

In [28]:
#arrays are very particular about having 1 data type for the elements in the list. Lists are more accommodating. 

py_list = [1, 1.5, 'A']
np_array = np.array(py_list)

py_list[0] = "Banana" #replace elements

In [29]:
py_list

['Banana', 1.5, 'A']

In [30]:
np_array

array(['1', '1.5', 'A'], dtype='<U32')

## 2.3 Adding a number

In [34]:
py_list2 = [1, 2, 3, 4, 5]
np_array2 = np.array(py_list2)         

In [35]:
py_list2 + 25    

TypeError: can only concatenate list (not "int") to list

In [36]:
np_array2 + 25

array([26, 27, 28, 29, 30])

## 2.4 Adding another list

In [38]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

In [39]:
py_list_1 + py_list_2 #list concats

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [40]:
np_array_1 + np_array_2 #arrays operates like a matrix

array([11, 22, 33, 44, 55])

In [41]:
py_list_3 = ["sean","an", "jerry", "siyou", "lexuan", "yeting"]
py_list_4 = [10, 20, 30, 40, 50]

np_array_3 = np.array(py_list_3)
np_array_4 = np.array(py_list_4)

In [48]:
py_list_3 = ["sean","an", "jerry", "siyou", "lexuan", "yeting"]
py_list_4 = [[10, 20, 30, 40, 50],23]
cop = py_list_3.copy()
py_list_3.append(py_list_4) #append essentially concats 
cop.extend(py_list_4) #extend treats the second list as an element on its own
print(cop)
print(py_list_3)

['sean', 'an', 'jerry', 'siyou', 'lexuan', 'yeting', [10, 20, 30, 40, 50], 23]
['sean', 'an', 'jerry', 'siyou', 'lexuan', 'yeting', [[10, 20, 30, 40, 50], 23]]


## 2.5 Multiplying by a Number

In [50]:
yes = [1, 2, 3, 4, 5]
np_yes = np.array(yes)         

In [52]:
yes*3 #list combines the list itself n number of times.

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [53]:
np_yes*3 #array multiplies the elements within the list by n times.

array([ 3,  6,  9, 12, 15])

## 2.6 Squaring

In [56]:
no = [1, 2, 3, 4, 5]
no_array = np.array(no)

In [55]:
no**3

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [58]:
no_array**3 #array raise the power of the elements by n times.

array([  1,   8,  27,  64, 125])

## 2.7 Asking questions

In [65]:
ligma = [1, 2, 3, 4, 5, 6]
sigma = np.array(ligma)         

In [69]:
ligma == 3 #asking if the variable ligma is the same value as 3

False

In [70]:
ligma == [1, 2, 3, 4, 5, 6] 

True

In [71]:
sigma == 3

array([False, False,  True, False, False, False])

In [72]:
sigma > 3

array([False, False, False,  True,  True,  True])

## 2.8 Mathematics

In [73]:
mary = [1, 2, 3, 4, 5]
lamb = np.array(mary)         

In [74]:
sum(mary)

15

In [77]:
max(mary)

5

In [78]:
min(mary)

1

In [79]:
lamb.max()

5

In [80]:
lamb.mean()

3.0

In [81]:
lamb.std()

1.4142135623730951

# Exercises & Self-Assessment

In [ ]:



# Your solution here




## Footnotes