<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# What to expect in this chapter

# 1 Subsetting: Indexing and Slicing

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

In [2]:
import numpy as np
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

x = py_list  

x[0]   #indexing refers to selecting 1 element


'a1'

In [3]:
x[0:3]  #slicing refers to selecting a range of elements.
        #from index 0 (1st element) to index 3-1 = 2 (3rd element)

['a1', 'b2', 'c3']

In [4]:
x[2:6] #from index 2 (3rd element) to index 6-1 = 5 (6th element)

['c3', 'd4', 'e5', 'f6']

In [11]:
x[1:6:2]  #from index 1 (2nd element) to index 6-1 = 5 (6th element)
          #skipping at intervals of 2

['b2', 'd4', 'f6']

In [8]:
x[1:9:3] #from index 1 (2nd element) to index 9-1 = 8 (9th element)
         #skipping at intervals of 3

['b2', 'e5', 'h8']

In [9]:
x[5:] #from 6th element to the end

['f6', 'g7', 'h8', 'i9', 'j10']

In [10]:
x[:5] #from 1st element to the index 5-1 = 4 (5th element)

['a1', 'b2', 'c3', 'd4', 'e5']

In [12]:
x[5:2:-1] #from index 5 (6th element) to the index 2+1 = 3 (4th element)

['f6', 'e5', 'd4']

In [14]:
x[5:2]

[]

In [18]:
x[::-1] #reverses the list

['j10', 'i9', 'h8', 'g7', 'f6', 'e5', 'd4', 'c3', 'b2', 'a1']

In [19]:
x[::-2] #reverses the list, skipping intervals of 2

['j10', 'h8', 'f6', 'd4', 'b2']

## 1.2 Arrays only | Subsetting by masking

In [21]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array >= 3 

np_array[my_mask] #only show elements that is True to my question
                  #subsetting by masking only works with NumPy arrays.


array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
np_array[np_array >= 3] #cleaner, don't need to create new variable

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
np_array[~(np_array >= 3)] # '~' means 'NOT'

array([1, 2])

In [29]:
np_array[(np_array >= 3) & (np_array < 8)] # '~' means '&'

array([3, 4, 5, 6, 7])

In [30]:
np_array[(np_array < 3) | (np_array > 8)] # '|' means 'OR'

array([ 1,  2,  9, 10])

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

In [56]:
y = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

x = np.array(y)

In [33]:
y[-1] #nested list in last index

[10, 'J']

In [34]:
x[-1] #array is fussy about different types

array(['10', 'J'], dtype='<U21')

In [38]:
y[3][0] #first element within index 3 (4th element)

4

In [39]:
x[3,0]  #first element within index 3 (4th element)

'4'

In [41]:
y[:3] #1st element to index 3-1 = 2 (3rd element)

[[1, 'A'], [2, 'B'], [3, 'C']]

In [44]:
y[:3][0] #list slices 1st element to index 3-1 = 2 (3rd element)
         #but only picks element at index 0 (1st element)

[1, 'A']

In [49]:
x[:3,0] #array slices 1st element to index 3-1 = 2 (3rd element)
        #but only picks element at index 0 (1st element) of each nested list

array(['1', '2', '3'], dtype='<U21')

In [57]:
y[3:6][0] #list slices 3rd element to index 6-1 = 5 (6th element)
          #but only picks element at index 0 of the slice (3rd element)

[4, 'D']

In [59]:
x[3:6,0] #array slices 3rd element to index 6-1 = 5 (6th element)
         #but only picks element at index 0 (1st element) of each nested list

array(['4', '5', '6'], dtype='<U21')

## 1.4 Growing lists

In [50]:
w=[1, 2]*5 #list repeats itself n times
w

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [58]:
z=[1]
z.append(2)
z.append(3)
z.append(5)
z

[1, 2, 3, 5]

In [63]:
a = [1,2,3]
a.extend([4,5,6]) #extend concats the lists
a

[1, 2, 3, 4, 5, 6]

In [65]:
b = [1,2,3]
b.append([4,5,6]) #append incorpoates the new list as an element
b 

[1, 2, 3, [4, 5, 6]]

# Some loose ends

## 1.5 Tuples

In [70]:
d=(1, 2, 3)     #tuple are similar to lists, except they use ( )
                #cannot be changed after creation 
                #(i.e., they are immutable).
print(d[1])

2


In [71]:
# The following will NOT work 
d[0]=-1
d[0]+= [10]

TypeError: 'tuple' object does not support item assignment

In [73]:
e = [1,2,3]
e[0] = -1
print(e[0])

-1


## 1.6 Be VERY careful when copying

In [80]:
x=[1, 2, 3] #wrong way to copy
y=x
z=x

print(f'{id(x)},{id(y)},{id(z)}') #x, y, z have the same id

4660527552,4660527552,4660527552


In [81]:
x=[1, 2, 3] #right way to copy
y=x.copy()
z=x.copy()

y.append([4,5,6])
z.extend([4,5,6])
print(y)
print(z)

print(f'{id(x)},{id(y)},{id(z)}') #x, y, z have the different id

[1, 2, 3, [4, 5, 6]]
[1, 2, 3, 4, 5, 6]
4661066432,4661058496,4661040320


# Exercises & Self-Assessment

In [ ]:



# Your solution here




## Footnotes